### ISSUE TITLE
Not able to install plugins when adding Plugins via Wordpress

### ISSUE THREAD

**Issue by robertkeus** [brthrs/brthrs-vagrant-box#1]

**Comment by sebask** [comment]
@robertkeus Klopt het dat Kult hier problemen mee heeft? Ik kan wellicht vrijdag of maandag een geupdate Vagrant box maken.

**Comment by robertkeus** [comment]
Voor alsnog niet, maar kan wel komen. Ik heb er wel problemen mee.

**Comment by sebask** [comment]
Vooralsnog kun je dit oplossen door te "ftpen", zie https://github.com/brthrs/brthrs-vagrant-box/issues/2.

**Comment by sebask** [comment]
Also fixed in todays release. It's now possible to use ssh2 from within Wordpress to update and or install plugins and what not.
