### ISSUE TITLE
Not clear how to FTP to virtual machine

### ISSUE THREAD

**Issue by robertkeus** [brthrs/brthrs-vagrant-box#2]

**Comment by sebask** [comment]
The information provided by the `vagrant ssh-config` command can be used to ssh (ftp) in to the machine. Be sure to use the key since it uses key based authentication.

![2015-05-27 15_00_19](https://cloud.githubusercontent.com/assets/2178774/7836534/1c8c2cf0-0481-11e5-8081-0115452a7208.gif)

**Comment by sebask** [comment]
Our Brthrs wiki has been updated https://github.com/brthrs/wiki/wiki/Vagrant#connect-using-sftp.
