### ISSUE TITLE
Please add a Wiki how to restore a database with Vagrant

### ISSUE THREAD

**Issue by robertkeus** [brthrs/brthrs-vagrant-box#3]
Otherwise it's not possible for people as me to use this as a dev machine. I often need to to restore existing data from dev machines.

**Comment by sebask** [comment]
I will add this to the wiki in the future. In the meantime the best way is to ssh in to the machine and use mysql from the cli. Import the sql file which you have placed on the system though ssh. It's easier then it sounds.

More on it here; http://stackoverflow.com/questions/17666249/how-to-import-an-sql-file-using-the-command-line-in-mysql.

**Comment by sebask** [comment]
I added Adminer to the box (`/adminer`) which can be used to manage databases. Of course it's still possible to use MySQL from the CLI.
